from enum import auto, Flag

from core.action import Action

# class HockeyAction(Action):
#
#     GRAB_PUCK = auto()
#     SPIN_RANDOMLY = auto()
#     #
#     FULL_POWER = auto()
#     HALF_POWER = auto()
#     THIRD_OF_POWER = auto()
#     MIN_POWER = auto()
#     # pure direction
#     LEFT = auto()
#     RIGHT = auto()
#     # pure action
#     MOVE = auto()
#     SHOOT = auto()
#     # angles
#     RADIANS_0 = auto()
#     RADIANS_PI_TIMES_1_OVER_10 = auto()
#     RADIANS_PI_TIMES_2_OVER_10 = auto()
#     RADIANS_PI_TIMES_3_OVER_10 = auto()
#     RADIANS_PI_TIMES_4_OVER_10 = auto()
#     RADIANS_PI_TIMES_5_OVER_10 = auto()
#     RADIANS_PI_TIMES_6_OVER_10 = auto()
#     RADIANS_PI_TIMES_7_OVER_10 = auto()
#     RADIANS_PI_TIMES_8_OVER_10 = auto()
#     RADIANS_PI_TIMES_9_OVER_10 = auto()
#     RADIANS_PI_TIMES_10_OVER_10 = auto()
#
#     # shoot
#     # hard
#     # SHOOT_HARD_AHEAD = SHOOT | LEFT | FULL_POWER | RADIANS_0
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_1_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_1_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_1_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_1_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_2_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_2_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_2_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_2_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_3_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_3_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_3_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_3_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_4_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_4_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_4_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_4_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_5_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_5_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_6_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_6_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_7_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_7_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_8_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_8_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_9_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_9_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # SHOOT_HARD_TO_LEFT_PI_TIMES_10_OVER_10 = SHOOT | LEFT | FULL_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # SHOOT_HARD_TO_RIGHT_PI_TIMES_10_OVER_10 = SHOOT | RIGHT | FULL_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # # soft
#     # SHOOT_SOFT_AHEAD = SHOOT | LEFT | HALF_POWER | RADIANS_0
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_1_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_1_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_1_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_1_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_2_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_2_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_2_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_2_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_3_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_3_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_3_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_3_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_4_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_4_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_4_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_4_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_5_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_5_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_6_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_6_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_7_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_7_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_8_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_8_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_9_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_9_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # SHOOT_SOFT_TO_LEFT_PI_TIMES_10_OVER_10 = SHOOT | LEFT | HALF_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # SHOOT_SOFT_TO_RIGHT_PI_TIMES_10_OVER_10 = SHOOT | RIGHT | HALF_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # move
#     STOP = auto()
#     # fast
#     SPRINT = MOVE | LEFT | FULL_POWER | RADIANS_0
#     MOVE_FAST_GO_LEFT_PI_TIMES_1_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_1_OVER_10
#     MOVE_FAST_GO_RIGHT_PI_TIMES_1_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_1_OVER_10
#     MOVE_FAST_GO_LEFT_PI_TIMES_2_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_2_OVER_10
#     MOVE_FAST_GO_RIGHT_PI_TIMES_2_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_2_OVER_10
#     MOVE_FAST_GO_LEFT_PI_TIMES_3_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_3_OVER_10
#     MOVE_FAST_GO_RIGHT_PI_TIMES_3_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_3_OVER_10
#     MOVE_FAST_GO_LEFT_PI_TIMES_4_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_4_OVER_10
#     MOVE_FAST_GO_RIGHT_PI_TIMES_4_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_4_OVER_10
#     MOVE_FAST_GO_LEFT_PI_TIMES_5_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_5_OVER_10
#     MOVE_FAST_GO_RIGHT_PI_TIMES_5_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # MOVE_FAST_GO_LEFT_PI_TIMES_6_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # MOVE_FAST_GO_RIGHT_PI_TIMES_6_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # MOVE_FAST_GO_LEFT_PI_TIMES_7_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # MOVE_FAST_GO_RIGHT_PI_TIMES_7_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # MOVE_FAST_GO_LEFT_PI_TIMES_8_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # MOVE_FAST_GO_RIGHT_PI_TIMES_8_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # MOVE_FAST_GO_LEFT_PI_TIMES_9_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # MOVE_FAST_GO_RIGHT_PI_TIMES_9_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # MOVE_FAST_GO_LEFT_PI_TIMES_10_OVER_10 = MOVE | LEFT | FULL_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # MOVE_FAST_GO_RIGHT_PI_TIMES_10_OVER_10 = MOVE | RIGHT | FULL_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # easy
#     SKATE_CALMLY = MOVE | LEFT | HALF_POWER | RADIANS_0
#     SKATE_VERY_CALMLY = MOVE | LEFT | THIRD_OF_POWER | RADIANS_0
#     SKATE_MIN_SPEED = MOVE | LEFT | MIN_POWER | RADIANS_0
#     MOVE_EASY_GO_LEFT_PI_TIMES_1_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_1_OVER_10
#     MOVE_EASY_GO_RIGHT_PI_TIMES_1_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_1_OVER_10
#     MOVE_EASY_GO_LEFT_PI_TIMES_2_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_2_OVER_10
#     MOVE_EASY_GO_RIGHT_PI_TIMES_2_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_2_OVER_10
#     MOVE_EASY_GO_LEFT_PI_TIMES_3_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_3_OVER_10
#     MOVE_EASY_GO_RIGHT_PI_TIMES_3_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_3_OVER_10
#     MOVE_EASY_GO_LEFT_PI_TIMES_4_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_4_OVER_10
#     MOVE_EASY_GO_RIGHT_PI_TIMES_4_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_4_OVER_10
#     MOVE_EASY_GO_LEFT_PI_TIMES_5_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_5_OVER_10
#     MOVE_EASY_GO_RIGHT_PI_TIMES_5_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_5_OVER_10
#     # MOVE_EASY_GO_LEFT_PI_TIMES_6_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # MOVE_EASY_GO_RIGHT_PI_TIMES_6_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_6_OVER_10
#     # MOVE_EASY_GO_LEFT_PI_TIMES_7_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # MOVE_EASY_GO_RIGHT_PI_TIMES_7_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_7_OVER_10
#     # MOVE_EASY_GO_LEFT_PI_TIMES_8_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # MOVE_EASY_GO_RIGHT_PI_TIMES_8_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_8_OVER_10
#     # MOVE_EASY_GO_LEFT_PI_TIMES_9_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # MOVE_EASY_GO_RIGHT_PI_TIMES_9_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_9_OVER_10
#     # MOVE_EASY_GO_LEFT_PI_TIMES_10_OVER_10 = MOVE | LEFT | HALF_POWER | RADIANS_PI_TIMES_10_OVER_10
#     # MOVE_EASY_GO_RIGHT_PI_TIMES_10_OVER_10 = MOVE | RIGHT | HALF_POWER | RADIANS_PI_TIMES_10_OVER_10
#
#     def __str__(self):
#         return self.name
#

class HockeyAction(Action):

    FULL_POWER = auto()
    HALF_POWER = auto()
    THIRD_OF_POWER = auto()
    MIN_POWER = auto()
    NO_POWER = auto()
    KEEP_SPEED = auto()
    # pure direction
    LEFT = auto()
    RIGHT = auto()
    # pure action
    MOVE = auto()
    SHOOT = auto()
    # angles
    RADIANS_0 = auto()
    RADIANS_PI_TIMES_1_OVER_10 = auto()
    RADIANS_PI_TIMES_2_OVER_10 = auto()
    RADIANS_PI_TIMES_3_OVER_10 = auto()
    RADIANS_PI_TIMES_4_OVER_10 = auto()
    RADIANS_PI_TIMES_5_OVER_10 = auto()
    RADIANS_PI_TIMES_6_OVER_10 = auto()
    RADIANS_PI_TIMES_7_OVER_10 = auto()
    RADIANS_PI_TIMES_8_OVER_10 = auto()
    RADIANS_PI_TIMES_9_OVER_10 = auto()
    RADIANS_PI_TIMES_10_OVER_10 = auto()

    #
    GRAB_PUCK = auto()
    ALIGN_WITH_PUCK = auto()
    # turn
    TURN_LEFT = MOVE | LEFT | KEEP_SPEED | RADIANS_PI_TIMES_2_OVER_10
    TURN_HARD_LEFT = MOVE | LEFT | KEEP_SPEED | RADIANS_PI_TIMES_4_OVER_10
    TURN_RIGHT = MOVE | RIGHT | KEEP_SPEED | RADIANS_PI_TIMES_2_OVER_10
    TURN_HARD_RIGHT = MOVE | RIGHT | KEEP_SPEED | RADIANS_PI_TIMES_4_OVER_10
    # speeds
    STOP =  MOVE | LEFT | NO_POWER | RADIANS_0
    # SPRINT = MOVE | LEFT | FULL_POWER | RADIANS_0
    # SKATE_CALMLY = MOVE | LEFT | HALF_POWER | RADIANS_0
    # SKATE_VERY_CALMLY = MOVE | LEFT | THIRD_OF_POWER | RADIANS_0
    SKATE_MIN_SPEED = MOVE | LEFT | MIN_POWER | RADIANS_0

    def __str__(self):
        return self.name

if __name__ == "__main__":
    print(HockeyAction.MIN_POWER)


