from enum import auto, Flag

from core.action import Action

class HockeyAction(Action):

    NOOP = auto() # no operation
    # move forward
    MOVE_RANDOM_SPEED = auto()
    #
    GRAB_PUCK = auto()
    SPIN_RANDOMLY = auto()
    #
    HARD = auto()
    SOFT = auto()
    # pure direction
    LEFT = auto()
    RIGHT = auto()
    # pure action
    MOVE = auto()
    SHOOT = auto()
    # angles
    RADIANS_0 = auto()
    RADIANS_PI_TIMES_1_OVER_10 = auto()
    RADIANS_PI_TIMES_2_OVER_10 = auto()
    RADIANS_PI_TIMES_3_OVER_10 = auto()
    RADIANS_PI_TIMES_4_OVER_10 = auto()
    RADIANS_PI_TIMES_5_OVER_10 = auto()
    RADIANS_PI_TIMES_6_OVER_10 = auto()
    RADIANS_PI_TIMES_7_OVER_10 = auto()
    RADIANS_PI_TIMES_8_OVER_10 = auto()
    RADIANS_PI_TIMES_9_OVER_10 = auto()
    RADIANS_PI_TIMES_10_OVER_10 = auto()

    # shoot
    # hard
    SHOOT_HARD_AHEAD = SHOOT | LEFT | HARD | RADIANS_0
    SHOOT_HARD_TO_LEFT_PI_TIMES_1_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_1_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_1_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_1_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_2_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_2_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_2_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_2_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_3_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_3_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_3_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_3_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_4_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_4_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_4_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_4_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_5_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_5_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_5_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_5_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_6_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_6_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_6_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_6_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_7_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_7_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_7_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_7_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_8_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_8_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_8_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_8_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_9_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_9_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_9_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_9_OVER_10
    SHOOT_HARD_TO_LEFT_PI_TIMES_10_OVER_10 = SHOOT | LEFT | HARD | RADIANS_PI_TIMES_10_OVER_10
    SHOOT_HARD_TO_RIGHT_PI_TIMES_10_OVER_10 = SHOOT | RIGHT | HARD | RADIANS_PI_TIMES_10_OVER_10
    # soft
    SHOOT_SOFT_AHEAD = SHOOT | LEFT | SOFT | RADIANS_0
    SHOOT_SOFT_TO_LEFT_PI_TIMES_1_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_1_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_1_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_1_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_2_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_2_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_2_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_2_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_3_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_3_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_3_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_3_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_4_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_4_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_4_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_4_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_5_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_5_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_5_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_5_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_6_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_6_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_6_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_6_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_7_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_7_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_7_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_7_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_8_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_8_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_8_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_8_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_9_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_9_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_9_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_9_OVER_10
    SHOOT_SOFT_TO_LEFT_PI_TIMES_10_OVER_10 = SHOOT | LEFT | SOFT | RADIANS_PI_TIMES_10_OVER_10
    SHOOT_SOFT_TO_RIGHT_PI_TIMES_10_OVER_10 = SHOOT | RIGHT | SOFT | RADIANS_PI_TIMES_10_OVER_10
    # move
    # fast
    SPRINT = MOVE | LEFT | HARD | RADIANS_0
    MOVE_FAST_GO_LEFT_PI_TIMES_1_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_1_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_1_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_1_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_2_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_2_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_2_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_2_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_3_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_3_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_3_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_3_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_4_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_4_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_4_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_4_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_5_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_5_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_5_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_5_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_6_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_6_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_6_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_6_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_7_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_7_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_7_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_7_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_8_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_8_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_8_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_8_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_9_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_9_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_9_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_9_OVER_10
    MOVE_FAST_GO_LEFT_PI_TIMES_10_OVER_10 = MOVE | LEFT | HARD | RADIANS_PI_TIMES_10_OVER_10
    MOVE_FAST_GO_RIGHT_PI_TIMES_10_OVER_10 = MOVE | RIGHT | HARD | RADIANS_PI_TIMES_10_OVER_10
    # easy
    SKATE_CALMLY = MOVE | LEFT | SOFT | RADIANS_0
    MOVE_EASY_GO_LEFT_PI_TIMES_1_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_1_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_1_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_1_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_2_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_2_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_2_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_2_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_3_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_3_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_3_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_3_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_4_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_4_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_4_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_4_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_5_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_5_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_5_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_5_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_6_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_6_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_6_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_6_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_7_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_7_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_7_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_7_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_8_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_8_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_8_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_8_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_9_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_9_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_9_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_9_OVER_10
    MOVE_EASY_GO_LEFT_PI_TIMES_10_OVER_10 = MOVE | LEFT | SOFT | RADIANS_PI_TIMES_10_OVER_10
    MOVE_EASY_GO_RIGHT_PI_TIMES_10_OVER_10 = MOVE | RIGHT | SOFT | RADIANS_PI_TIMES_10_OVER_10
